# 전자정부 표준프레임워크 Spring Boot 설정
# eGovFrame Spring Boot Configuration

server:
  # 서버 포트 설정
  # Server port configuration
  port: 8080

spring:
  main:
    # 수동 Bean이 자동 Bean을 오버라이딩하게 설정
    # 개발 시 커스텀 Bean이 기본 Bean을 대체할 수 있도록 허용
    # Allow manual beans to override automatic beans
    # Enables custom beans to replace default beans during development
    allow-bean-definition-overriding: true
    
  jpa:
    # Open-in-View 패턴 설정 (OSIV)
    # true(기본값): 사용자에게 응답 또는 view가 렌더링될 때까지 영속성 컨텍스트 유지
    # false: 트랜잭션이 종료될 때 영속성 컨텍스트 종료 (성능상 권장)
    #
    # Open-in-View pattern configuration (OSIV)
    # true(default): Keep persistence context until response or view rendering to user
    # false: Close persistence context when transaction ends (recommended for performance)
    open-in-view: false

# 전자정부 프레임워크 글로벌 설정 (심플백엔드 호환)
# 주의: Globals.* 프로퍼티는 자동으로 camelCase로 변환됩니다
# 예시: Globals.page-unit → Globals.PageUnit, Globals.db-type → Globals.DbType
# 활용: propertiesService.getString("Globals.PageUnit")
#
# eGovFrame Global Configuration (Simple-backend compatible)
# Note: Globals.* properties are automatically converted to camelCase
# Example: Globals.page-unit → Globals.PageUnit, Globals.db-type → Globals.DbType
# Usage: propertiesService.getString("Globals.PageUnit")
Globals:
  # 페이징 설정
  # Pagination settings
  page-unit: 10
  page-size: 10
  
  # 파일 업로드 설정
  # File upload settings
  posbl-atch-file-size: 5242880
  file-store-path: "./files"
  added-options: false
  
  # 데이터베이스 설정(hsql,mysql,oracle)
  # Database settings
  db-type: "hsql"

  # HSQL 설정
  # HSQL configuration
  hsql:
    script-location: "classpath:/db/sampledb.sql"

  # MySQL 설정
  # MySQL configuration
  mysql:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/egovframe"
    user-name: "egovframe"
    password: "egovframe"
    
  # Oracle 설정
  # Oracle configuration
  oracle:
    driver-class-name: "oracle.jdbc.driver.OracleDriver"
    url: "jdbc:oracle:thin:@127.0.0.1:1521:sampledb"
    user-name: "sa"
    password: ""